import './globals.css'
import '../node_modules/nes.css/css/nes.min.css'
import { Press_Start_2P } from 'next/font/google'

const pressStart2p = Press_Start_2P({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body className={pressStart2p.className}>{children}</body>
    </html>
  )
}
